### PR TITLE
fixed compilation errors on xcode 12.4

### PR DESCRIPTION
**Pull request by pobengtsson**
Hi @nalexn 

I tried to use 5.7.6 but got compilation errors in the new features (ActionSheet/Alert).
I run Xcode 12.4 because I cannot upgrade to Big Sur (for other reasons) and therefore cannot upgrade to 12.5 in the near future.

I made this PR that compiles and completes all the tests on Xcode 12.4.

Would you consider merging this PR after checking that it compiles on Xcode 12.5?

Thanks!

### CODE REVIEW

**Comment by nalexn** [comment]
Hey @pobengtsson , thanks for the PR, I've released the hotfix

**Comment by pobengtsson** [comment]
Great! Thanks a lot!
