### ISSUE TITLE
0.9.2 - cannot find type 'ToolbarPlacement' in scope

### ISSUE THREAD

**Issue by LucasColomer** [nalexn/ViewInspector#199]
Hi ! 

I recently upgraded to version 0.9.2.
Unfortunately, when building on gitlab, I get these errors: 

`❌  /Users/username/Library/Developer/Xcode/DerivedData/ProjectName-enljwdtuheospgflhgetanmpceiw/SourcePackages/checkouts/ViewInspector/Sources/ViewInspector/Modifiers/NavigationBarModifiers.swift:54:11: cannot find type 'ToolbarPlacement' in scope
extension ToolbarPlacement: BinaryEquatable { }
          ^~~~~~~~~~~~~~~~
❌  /Users/username/Library/Developer/Xcode/DerivedData/ProjectName-enljwdtuheospgflhgetanmpceiw/SourcePackages/checkouts/ViewInspector/Sources/ViewInspector/Modifiers/NavigationBarModifiers.swift:19:72: cannot find 'ToolbarPlacement' in scope
                        path: "modifier|bars", value: modifier, type: [ToolbarPlacement].self)
                                                                       ^~~~~~~~~~~~~~~~
❌  /Users/username/Library/Developer/Xcode/DerivedData/ProjectName-enljwdtuheospgflhgetanmpceiw/SourcePackages/checkouts/ViewInspector/Sources/ViewInspector/Modifiers/NavigationBarModifiers.swift:21:39: cannot infer contextual base in reference to member 'navigationBar'
                return bars.contains(.navigationBar)
                                     ~^~~~~~~~~~~~~
❌  /Users/username/Library/Developer/Xcode/DerivedData/ProjectName-enljwdtuheospgflhgetanmpceiw/SourcePackages/checkouts/ViewInspector/Sources/ViewInspector/Modifiers/NavigationBarModifiers.swift:54:11: cannot find type 'ToolbarPlacement' in scope
extension ToolbarPlacement: BinaryEquatable { }
          ^~~~~~~~~~~~~~~~
❌  /Users/username/Library/Developer/Xcode/DerivedData/ProjectName-enljwdtuheospgflhgetanmpceiw/SourcePackages/checkouts/ViewInspector/Sources/ViewInspector/Modifiers/NavigationBarModifiers.swift:19:72: cannot find 'ToolbarPlacement' in scope
                        path: "modifier|bars", value: modifier, type: [ToolbarPlacement].self)
                                                                       ^~~~~~~~~~~~~~~~
❌  /Users/username/Library/Developer/Xcode/DerivedData/ProjectName-enljwdtuheospgflhgetanmpceiw/SourcePackages/checkouts/ViewInspector/Sources/ViewInspector/Modifiers/NavigationBarModifiers.swift:21:39: cannot infer contextual base in reference to member 'navigationBar'
                return bars.contains(.navigationBar)`

When I build from xCode I get the same errors.

When I upgrade to 0.9.1 I don't get these problems anymore.
I'm not sure if anyone has ever had this problem and managed to fix it? 

I'm using swift package manager with this setting ViewInspector 0.9.1 - Next Major - https://github.com/nalexn/ViewInspector

**Comment by nalexn** [comment]
Hey @LucasColomer, make sure you're using Xcode 14.0, this is the requirement for [v0.9.2](https://github.com/nalexn/ViewInspector/releases/tag/0.9.2)

**Comment by rhwood** [comment]
I get this same error using Xcode 14.0.1. It appears that ViewInspector requires building the tested project for macOS other than 13.

**Comment by rhwood** [comment]
I created #206, which I think fixes this, since I could only recreate this using the "My Mac (Mac Catalyst)" build target, but not the "My Mac" build target.

**Comment by JValderramaN** [comment]
HI

maybe is not related, but there is one struct called the same from SwiftUI
`struct ToolbarPlacement`
https://developer.apple.com/documentation/swiftui/toolbarplacement

Here is in the repo: https://github.com/nalexn/ViewInspector/blob/ac7df67c4e0593470eda90a550f8493a81609745/Sources/ViewInspector/Modifiers/NavigationBarModifiers.swift#L4

Best regards

**Comment by rhwood** [comment]
> HI
> 
> maybe is not related, but there is one struct called the same from SwiftUI `struct ToolbarPlacement` https://developer.apple.com/documentation/swiftui/toolbarplacement
> 
> Here is in the repo:
> 
> https://github.com/nalexn/ViewInspector/blob/ac7df67c4e0593470eda90a550f8493a81609745/Sources/ViewInspector/Modifiers/NavigationBarModifiers.swift#L4
> 
> Best regards

Apple introduced ToolbarPlacement in iOS/iPadOS/Mac Catalyst/tvOS 16, macOS 13, and watchOS 9. It is defined in this project such that Apple's definition is used in macOS 13, but not cause "missing symbol" compilation failures on macOS 12. The problem is that Mac Catalyst is not macOS in the conditional compilation macros, so the missing symbol fix doesn't get applied when the target is Mac Catalyst on macOS 12.
